# app/data.py
# This file contains all the mock product data for the application.

MOCK_PRODUCT_CATALOG = [
    # Mobiles with detailed specs
    { "id": 1, "title": "Motorola g45 5G", "brand": "Motorola", "rating": 4.5, "reviews": 180938, "isAssured": True, "tags": ["motorola", "5g", "phone", "mobile"], "specs": {"RAM": "6 GB", "ROM": "128 GB", "Display": "6.5 inch Full HD+", "Camera": "50MP", "Battery": "5000 mAh"}, "price": 11999, "originalPrice": 14999, "delivery": "Tomorrow", "bankOffer": "Bank Offer" },
    { "id": 2, "title": "Samsung Galaxy F05", "brand": "Samsung", "rating": 4.3, "reviews": 56324, "isAssured": True, "tags": ["samsung", "galaxy", "phone", "mobile"], "specs": {"RAM": "4 GB", "ROM": "64 GB", "Display": "6.5 inch HD+", "Camera": "13MP", "Battery": "6000 mAh"}, "price": 6249, "originalPrice": 9999, "delivery": "In 2 days", "bankOffer": "Bank Offer" },
    { "id": 3, "title": "POCO C75 5G", "brand": "POCO", "rating": 4.4, "reviews": 72791, "isAssured": True, "tags": ["poco", "5g", "phone", "mobile"], "specs": {"RAM": "4 GB", "ROM": "64 GB", "Display": "6.58 inch Full HD+", "Camera": "50MP", "Battery": "5000 mAh"}, "price": 7699, "originalPrice": 10999, "delivery": "Tomorrow", "bankOffer": "No Cost EMI" },
    { "id": 8, "title": "Apple iPhone 15", "brand": "Apple", "rating": 4.9, "reviews": 210500, "isAssured": True, "tags": ["apple", "iphone", "15", "phone", "mobile"], "specs": {"ROM": "128 GB", "Display": "6.1 inch Super Retina XDR", "Camera": "48MP", "Processor": "A16 Bionic Chip"}, "price": 71999, "originalPrice": 79900, "delivery": "Today", "bankOffer": "Bank Offer" },
    # Laptops
    { "id": 10, "title": "HP Pavilion Gaming Laptop", "brand": "HP", "rating": 4.7, "reviews": 15032, "isAssured": True, "tags": ["hp", "laptop", "gaming", "ryzen", "electronics"], "specs": {"Processor": "AMD Ryzen 5", "RAM": "8 GB", "Storage": "512 GB SSD", "Graphics": "NVIDIA GTX 1650"}, "price": 54990, "originalPrice": 69990, "delivery": "In 2 days", "bankOffer": "No Cost EMI" },
    { "id": 19, "title": "Dell Inspiron 15 Laptop", "brand": "Dell", "rating": 4.5, "reviews": 9876, "isAssured": True, "tags": ["dell", "laptop", "inspiron", "i5", "electronics"], "specs": {"Processor": "Intel Core i5", "RAM": "16 GB", "Storage": "1 TB SSD", "Graphics": "Intel Iris Xe"}, "price": 62990, "originalPrice": 75990, "delivery": "In 3 days", "bankOffer": "Bank Offer" },
    { "id": 30, "title": "Macbook Air M2", "brand": "Apple", "rating": 4.9, "reviews": 12034, "isAssured": True, "tags": ["macbook", "apple", "laptop", "m2", "electronics"], "specs": {"Processor": "Apple M2 Chip", "RAM": "8 GB", "Storage": "256 GB SSD", "Display": "Liquid Retina"}, "price": 99990, "originalPrice": 114900, "delivery": "Tomorrow", "bankOffer": "Bank Offer" },
    # Headphones
    { "id": 11, "title": "Sony WH-1000XM5 Wireless Headphones", "brand": "Sony", "rating": 4.9, "reviews": 22010, "isAssured": True, "tags": ["sony", "headphones", "wireless", "noise cancelling", "electronics", "audio"], "specs": {"Type": "Over-Ear", "Connectivity": "Bluetooth", "Battery": "30 Hours"}, "price": 29990, "originalPrice": 34990, "delivery": "Today", "bankOffer": "Bank Offer" },
    { "id": 15, "title": "boAt Airdopes 141 Bluetooth Earbuds", "brand": "boAt", "rating": 4.2, "reviews": 250102, "isAssured": True, "tags": ["boat", "airdopes", "earbuds", "headphones", "bluetooth", "audio", "electronics"], "specs": {"Type": "In-Ear", "Connectivity": "Bluetooth", "Battery": "42 Hours"}, "price": 1299, "originalPrice": 4490, "delivery": "Tomorrow", "bankOffer": "Special Offer" },
    # T-Shirts
    { "id": 4, "title": "HRX Men Solid Training T-Shirt", "brand": "HRX", "rating": 4.2, "reviews": 12450, "isAssured": False, "tags": ["hrx", "men", "t-shirt", "training", "solid", "red", "sportswear", "fashion"], "specs": {"Size": "M", "Fabric": "Polyester", "Fit": "Regular"}, "price": 599, "originalPrice": 999, "delivery": "In 3 days", "bankOffer": "Special Offer" },
    { "id": 26, "title": "Nike Men's Dri-FIT T-Shirt", "brand": "Nike", "rating": 4.7, "reviews": 34012, "isAssured": True, "tags": ["nike", "men", "t-shirt", "dri-fit", "sportswear", "fashion"], "specs": {"Size": "L", "Fabric": "Polyester", "Fit": "Regular"}, "price": 1299, "originalPrice": 1999, "delivery": "Tomorrow", "bankOffer": "Bank Offer" },
]
